---
- name: Install and configure Apache
  hosts: lamp_servers
  become: true

  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is running and enabled
      service:
        name: apache2
        state: started
        enabled: true

    - name: Enable Apache modules
      command: "a2enmod {{ item }}"
      with_items: "{{ apache_modules }}"
      notify: restart apache

    - name: Create document root directory
      file:
        path: "{{ document_root }}"
        state: directory
        owner: "www-data"
        group: "www-data"
        mode: '0755'

    - name: Configure VirtualHost from template
      template:
        src: "../templates/vhost.conf.j2"
        dest: "/etc/apache2/sites-available/{{ domain_name }}.conf"
      notify: reload apache

    - name: Enable the new site
      command: "a2ensite {{ domain_name }}.conf"
      notify: reload apache

    - name: Disable default Apache site
      command: "a2dissite 000-default.conf"
      notify: reload apache

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted

    - name: reload apache
      service:
        name: apache2
        state: reloaded
