---
- name: Install and configure PHP
  hosts: lamp_servers
  become: true

  tasks:
    - name: Add Ondrej PHP repository
      apt_repository:
        repo: "ppa:ondrej/php"
        state: present

    - name: Update apt cache after adding repository
      apt:
        update_cache: yes

    - name: Install PHP and Apache integration
      apt:
        name:
          - "php{{ php_version }}"
          - "libapache2-mod-php{{ php_version }}"
        state: present

    - name: Install PHP extensions
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ php_extensions }}"

    - name: Create PHP test page from template
      template:
        src: "../templates/index.php.j2"
        dest: "{{ document_root }}/index.php"
        owner: "www-data"
        group: "www-data"
        mode: '0644'
      notify: reload apache

  handlers:
    - name: reload apache
      service:
        name: apache2
        state: reloaded
